import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      // Precache static assets that aren't fingerprinted by the build.
      includeAssets: ['icon.svg', 'logo.svg', 'robots.txt', 'llms-full.txt'],
      // Generate real cross-platform icons from public/icon.svg:
      //   minimal-2023 → PNG 64/192/512 (transparent) + 512 maskable + 180 apple-touch + favicon.
      // overrideManifestIcons replaces the manifest icons[] with those PNG entries,
      // and htmlPreset '2023' injects <link rel="apple-touch-icon"> + favicon links into
      // index.html — the piece Safari needs (it ignores manifest icons). This is what
      // makes the app installable on iPhone/iPad, Android, Samsung Internet, and Windows.
      pwaAssets: {
        image: 'public/icon.svg',
        preset: 'minimal-2023',
        htmlPreset: '2023',
        overrideManifestIcons: true,
        injectThemeColor: true,
      },
      manifest: {
        id: '/',
        name: 'Welcome to the Table',
        short_name: 'The Table',
        description:
          'Discover verified Black-owned restaurants and stores across Greater Houston — a seat at the table for everybody.',
        lang: 'en',
        dir: 'ltr',
        start_url: '/',
        scope: '/',
        display: 'standalone',
        // iOS ignores display_override but Android/desktop use it to prefer the
        // window-controls/minimal-ui chain, falling back to standalone.
        display_override: ['standalone', 'minimal-ui'],
        orientation: 'portrait',
        categories: ['food', 'lifestyle', 'travel'],
        background_color: '#1A0E1F',
        theme_color: '#1A0E1F',
        // icons[] is generated by pwaAssets (overrideManifestIcons).
      },
    }),
  ],
});
